name: build-and-deploy

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: devops-app
  AWS_ACCOUNT_ID: 717491933397

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

- name: Deploy to EC2
  run: |
    echo "${{ secrets.EC2_SSH_KEY }}" > cicd-key.pem
    chmod 600 cicd-key.pem

    for host in 65.0.122.7 3.108.64.26 13.233.155.3
    do
      echo "Deploying to $host"
      ssh -o StrictHostKeyChecking=no -i cicd-key.pem ubuntu@$host << 'EOF'
        sudo apt-get update -y && sudo apt-get install -y docker.io
        sudo snap install aws-cli --classic
        sudo systemctl start docker
        aws ecr get-login-password --region ap-south-1 | sudo docker login --username AWS --password-stdin 717491933397.dkr.ecr.ap-south-1.amazonaws.com
        sudo docker pull 717491933397.dkr.ecr.ap-south-1.amazonaws.com/devops-app:latest
        sudo docker stop app || true
        sudo docker rm app || true
        sudo docker run -d --name app -p 80:80 717491933397.dkr.ecr.ap-south-1.amazonaws.com/devops-app:latest
      EOF
    done
