name: Day 6 CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: BUILD
        run: |
          docker build -t bnuthana/my-first-app:${{ github.sha }} -t bnuthana/my-first-app:latest .

      - name: TEST
        run: |
          docker run -d -p 8080:80 --name test-app bnuthana/my-first-app:latest
          sleep 10
          curl -f http://localhost:8080
          docker rm -f test-app

      - name: PUSH to Docker Hub
        run: |
          docker push bnuthana/my-first-app:${{ github.sha }}
          docker push bnuthana/my-first-app:latest

      - name: DEPLOY to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull bnuthana/my-first-app:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d -p 8080:80 --name my-app --restart always bnuthana/my-first-app:latest